rrpBuildImage {
    projectKey = 'docker-gluster-plugin'
    ecrRegistry = "280211473891.dkr.ecr.us-west-2.amazonaws.com"

    dockerBuildOptions = ['--build-arg GIT_COMMIT=$GIT_COMMIT']

    infra = [
        stackName: 'RRP-CodePipeline-RRP-Gluster-Plugin'
    ]
}